spring:
  profiles:
    active: git
  application:
    name: config-server
server:
  port: 8888
---

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health